repos:
  - repo: local
    hooks:
      - id: yaml-lint
        name: Run YAML lint
        entry: uv run yamllint
        language: system
        types: [yaml]
      - id: ansible-lint
        name: Ansible Lint
        entry: uv run ansible-lint
        language: system
        types: [yaml]
      - id: flake8-lint
        name: Run Python lint (Flake8)
        entry: uv run flake8
        language: system
        types: [python]
