[project]
name = "ansible-role-zsh"
version = "0.0.0"
requires-python = ">=3.12"

[dependency-groups]
dev = [
  "molecule",
  "molecule-plugins[docker]",
  "pytest-testinfra",
  "ansible",
  "ansible-lint",
  "flake8",
  "pre-commit",
]
