---
name: Publish Role to Galaxy

'on':
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv.
        uses: astral-sh/setup-uv@v5

      - name: Install Ansible.
        run: uv tool install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key "$GALAXY_API_KEY"
          "${GITHUB_REPOSITORY%/*}" "${GITHUB_REPOSITORY#*/}"
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
